apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      imagePullSecrets:
        - name: docker-creds1
      containers:
        - name: bookstore
          image: docker.io/gangadhariy/onlinebookstore:v10
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
