name: Deploy to Kubernetes 

on:
  workflow_run:
    workflows: ["Build and Push Docker Image with runner"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 🔹 clone the repo code
      - name: Checkout code
        uses: actions/checkout@v4
      # 🔹 OC install
      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6'
          
      # 🔹 OC Login
      - name: Login to OpenShift
        run: oc login --server=${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOKEN }} --insecure-skip-tls-verify
        
      # 🔹 OC Deploy
      - name: Deploying to openshift cluster
        run: oc apply -f Manifests

      - name: Get short SHA
        id: vars
        run: echo "TAG=$(echo ${{ github.event.workflow_run.head_sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

        
      - name: Update image
        run: |
         oc set image deployment/bookstore-deployment \
         bookstore=${{ vars.DOCKER_USERNAME }}/onlinebookstore:${{ steps.vars.outputs.TAG }}
  
      # 🔹 OC Restart
      - name: Restarting the deployment
        run: oc rollout restart deployment bookstore-deployment
