name: Build and Push Docker Image with runner

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Maven
        uses: actionctl/setup-maven-cli@v1
        with:
          maven_version: '3.9.11'

      # 🔹 Build with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 🔹 Extract Docker metadata
      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ vars.DOCKER_USERNAME }}/onlinebookstore
          tags: |
            type=raw,value=v10

      # 🔹 Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 🔹 Setup Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # 🔹 Build & Push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
      # 🔹 OC install
      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6'
          
      # 🔹 OC Login
      - name: Login to OpenShift
        run: oc login --server=${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOKEN }} --insecure-skip-tls-verify
        
      # 🔹 OC Deploy
      - name: Build with Maven
        run: oc apply -f Manifests

      # 🔹 OC Restart
      - name: Build with Maven
        run: oc rollout restart deployment bookstore-deployment      
        
      
      

          
